Request.Web/Request.Web/Controllers/HomeController.cs
using System.Linq;
using System.Web.Mvc;
using Request.Contract;
using Request.Contract.Services;
using Request.Web.Authorization;

namespace Request.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IRequestService _requestService;
        private User _currentUser;

        //public User CurrentEmployee => _currentUser ?? (_currentUser = ControllerContext.HttpContext.GetOfficeParkingIdentity().User);

        public HomeController(IRequestService requestService)
        {
            _requestService = requestService;
        }

        public ActionResult Index()
        {
            var requests = _requestService.GetRequestsByUserid(1);
            return View(requests);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Request.Web/Request.Web/Controllers/RequestController.cs
using System.Web.Mvc;

namespace Request.Web.Controllers
{
    public class RequestController : Controller
    {
        // GET: Request
        public ActionResult CreateRequest()
        {
            return View(new Contract.Request());
        }
    }
}

Request.Web/Request.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Request.Web/Request.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Request.Web/Request.Web/Views/Home/Index.cshtml
@using Request.Web.Models
@model IEnumerable<Request.Contract.Request>
@{
    ViewBag.Title = "Home Page";
}

<div id="tabContainer" class="input_group">
    @{
        var tabButtons = new List<FilterButton>();
        if (User.IsInRole("User") || User.IsInRole("Administrator"))
        {
            tabButtons.Add(new FilterButton { IsActive = true, Id = "myTab", Href = "", Label = "My" });
        }
        if (User.IsInRole("Assistant") || User.IsInRole("Administrator"))
        {
            tabButtons.Add(new FilterButton { IsActive = true, Id = "allTab", Href = "", Label = "All" });
        }

        <div id="filterTabs" class="input_group">
                @foreach (var button in tabButtons)
                {
                    <a id="@button.Id" class="uui_button @(button.IsActive ? "filter_btn_active" : "filter_btn")" href="@button.Href">@button.Label</a>
                }
        </div>
    }
    <div id="actionTabs" class="input_group">
        @if(true)//(User.IsInRole("User"))
        {
            <a href="@Url.Action("CreateRequest", "Request")" class="uui_button action_btn">New Request</a>
        }
    </div>
</div>

<div id="requestList">
    <table class="uui-table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>CreationDate</th>
            <th>Status</th>
            <th>Assistant</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
            @foreach (var req in @Model)
            {
                <tr>
                    <td>@req.Id</td>
                    <td>@req.Type.Name</td>
                    <td>@req.DateOfCreation</td>
                    <td>@req.Status.ToString()</td>
                    <td>@req.Assistant.Name</td>
                    <td></td>
                </tr>
            }
        </tbody>
    </table>
</div>